modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "solaris"
version = "${mod_version}"
displayName = "${display_name}"
authors = "${authors}"
description = "${description}"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.solaris]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.solaris]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.solaris]]
    modId = "epicfight"
    mandatory = true
    versionRange = "[18.3.6,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.solaris]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.18.2-5.0.9.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.solaris]]
    modId = "geckolib"
    mandatory = true
    versionRange = "[3.0.57,)"
    ordering = "NONE"
    side = "BOTH"
