name: Build Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
#  push:
#    branches:
#      -master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
#      - name: Checkout sources
#        uses: actions/checkout@v3
#      - name: validate gradle wrapper
#        uses: gradle/wrapper-validation-action@v1
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - name: Make Gradle wrapper accessible
#        run: chmod +x ./gradlew
#      - name: build
#        run: ./gradlew build
#      - run: echo "This job's status is ${{ job.status }}."
