name: Build Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
#  push:
#    branches:
#      -master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: build
        run: ./gradlew build
      - run: echo "This job's status is ${{ job.status }}."
